In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import seaborn as sns
import numpy as np

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/GaBP2/GaBP2_2024/4_Class_ML/SISSO_data_Class.csv')
#df = pd.read_csv('SISSO_data_Class.csv')
df.head()

,compound,BandGap_class,Volume,vand_rad_Avg,vand_rad_Min,vand_rad_Max,cov_rad_Avg,cov_rad_Min,cov_rad_Max,atom_rad_Avg,atom_rad_Min,atom_rad_Max,density_Avg,density_Min,density_Max
0,ZnGeN2,0,181.39,168.33,139,211,104.33,71,122,108.33,65,135,4.42,0.81,7.13
1,ZnGeN2,1,181.83,168.33,139,211,104.33,71,122,108.33,65,135,4.42,0.81,7.13
2,ZnGeN2,0,181.56,168.33,139,211,104.33,71,122,108.33,65,135,4.42,0.81,7.13
3,AlGaN2,1,178.46,175.33,155,187,104.67,71,122,106.67,65,130,3.14,0.81,5.91
4,AlGaN2,1,178.36,175.33,155,187,104.67,71,122,106.67,65,130,3.14,0.81,5.91

In [ ]:
df['Volume_density_Avg']= np.cbrt(df['Volume']*df['density_Avg'])
df['Volume_density_Avg']= df['Volume_density_Avg'].round(decimals = 2)
df['Volume_atom_rad_Avg']= np.cbrt(df['Volume']*df['atom_rad_Avg'])
df['Volume_atom_rad_Avg'] = df['Volume_atom_rad_Avg'].round(decimals = 2)
df.head()

,compound,BandGap_class,Volume,vand_rad_Avg,vand_rad_Min,vand_rad_Max,cov_rad_Avg,cov_rad_Min,cov_rad_Max,atom_rad_Avg,atom_rad_Min,atom_rad_Max,density_Avg,density_Min,density_Max,Volume_density_Avg,Volume_atom_rad_Avg
0,ZnGeN2,0,181.39,168.33,139,211,104.33,71,122,108.33,65,135,4.42,0.81,7.13,9.29,26.98
1,ZnGeN2,1,181.83,168.33,139,211,104.33,71,122,108.33,65,135,4.42,0.81,7.13,9.30,27.01
2,ZnGeN2,0,181.56,168.33,139,211,104.33,71,122,108.33,65,135,4.42,0.81,7.13,9.29,26.99
3,AlGaN2,1,178.46,175.33,155,187,104.67,71,122,106.67,65,130,3.14,0.81,5.91,8.24,26.70
4,AlGaN2,1,178.36,175.33,155,187,104.67,71,122,106.67,65,130,3.14,0.81,5.91,8.24,26.70

In [ ]:
df.shape

(144, 17)

In [ ]:
df1= df.copy()

In [ ]:
df2 = df1[['compound','BandGap_class','Volume_density_Avg','Volume_atom_rad_Avg']]
df2.head()

   compound  BandGap_class  Volume_density_Avg  Volume_atom_rad_Avg
0  ZnGeN2                0                9.29                26.98
1  ZnGeN2                1                9.30                27.01
2  ZnGeN2                0                9.29                26.99
3  AlGaN2                1                8.24                26.70
4  AlGaN2                1                8.24                26.70

In [ ]:
X1 = df2.drop(['compound','BandGap_class'], axis=1)
#X1 = df2.drop(['compound','BandGap_class','Volume_density_Avg'], axis=1)
X1.head(2)

   Volume_density_Avg  Volume_atom_rad_Avg
0                9.29                26.98
1                9.30                27.01

In [ ]:
Y1 = df2['BandGap_class']
Y1.head(2)

0    0
1    1
Name: BandGap_class, dtype: int64

## ML Model

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_squared_error
from sklearn import preprocessing
import matplotlib.pyplot as plt
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from scipy import stats
import seaborn as sns
from scipy.stats import norm
from scipy.stats import skew,kurtosis
#-----------------------------------------------------##
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.kernel_ridge import KernelRidge
from sklearn import ensemble
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.gaussian_process.kernels import RBF, ConstantKernel as C
from sklearn.gaussian_process.kernels import DotProduct, WhiteKernel
from sklearn.gaussian_process.kernels import DotProduct, WhiteKernel, Matern
#-------------------------------------------------------------------------
import csv
import os
from sklearn.cross_decomposition import PLSRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.linear_model import LogisticRegression
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_moons, make_circles, make_classification
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn import svm
import os
import csv
import pandas as pd
from shutil import copyfile
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [ ]:
import csv
import os
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.datasets import make_hastie_10_2
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from imblearn.over_sampling import SMOTE

In [ ]:
#X = preprocessing.scale(X2)
X = X1.copy()

In [ ]:
X.shape

(144, 2)

In [ ]:
X.head(2)

   Volume_density_Avg  Volume_atom_rad_Avg
0                9.29                26.98
1                9.30                27.01

In [ ]:
Y1.head(2)

0    0
1    1
Name: BandGap_class, dtype: int64

In [ ]:
pd.value_counts(Y1)

/tmp/ipykernel_406/2851655615.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(Y1)

BandGap_class
0    72
1    72
Name: count, dtype: int64

#   <h1><center>Decision Tree</center></h1>

In [ ]:
for n in range (0,20,1):
    # smote = SMOTE(sampling_strategy='minority', random_state=n)
    # X_sm, y_sm = smote.fit_resample(X, Y1)
    X_train, X_test, Y_train, Y_test = train_test_split(X, Y1, test_size=0.25, random_state=n)
    model = DecisionTreeClassifier(max_depth=10, max_features=2, random_state=n)
    model.fit(X_train, Y_train)
    y_train_pred = model.predict(X_test)
    accuracy = accuracy_score(Y_test,y_train_pred)
    #print("Test Accuracy score is", accuracy)
    with open('out.csv', mode='a') as out_file:
     out_writer = csv.writer(out_file, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
     out_writer.writerow(['%s' %n, '{}'.format(accuracy)])
     out_file.close()
from shutil import copyfile
copyfile('out.csv', 'out2.csv')
###here we import the out.csv file and printthe statistics
data_stat=pd.read_csv('out.csv',  names = ["Accuracy"])
print(data_stat.describe())
###############
#print(data_stat)
#Removing out.csv file
try:
    os.remove("out.csv")
except OSError:
    pass

        Accuracy
count  20.000000
mean    0.981944
std     0.024308
min     0.916667
25%     0.972222
50%     1.000000
75%     1.000000
max     1.000000

In [ ]:
# Accuracy
# count  20.000000
# mean    0.981944
# std     0.024308
# min     0.916667
# 25%     0.972222
# 50%     1.000000
# 75%     1.000000
# max     1.000000

## LogisticRegression

In [ ]:
import pandas as pd
import numpy as np
import csv
import os
from shutil import copyfile
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

for n in range(0, 20, 1):
    X_train, X_test, Y_train, Y_test = train_test_split(X, Y1, test_size=0.25, random_state=n)

    model = LogisticRegression(max_iter=1000, random_state=n)
    model.fit(X_train, Y_train)

    y_test_pred = model.predict(X_test)
    accuracy = accuracy_score(Y_test, y_test_pred)

    with open('out.csv', mode='a') as out_file:
        out_writer = csv.writer(out_file, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
        out_writer.writerow([n, accuracy])

copyfile('out.csv', 'out2.csv')

# Import the out.csv file and print the statistics
data_stat = pd.read_csv('out.csv', names=[ "Accuracy"])
print(data_stat.describe())

# Removing out.csv file
try:
    os.remove("out.csv")
except OSError:
    pass

        Accuracy
count  20.000000
mean    0.970833
std     0.021088
min     0.916667
25%     0.972222
50%     0.972222
75%     0.972222
max     1.000000

In [ ]:
#  Accuracy
# count  20.000000
# mean    0.970833
# std     0.021088
# min     0.916667
# 25%     0.972222
# 50%     0.972222
# 75%     0.972222
# max     1.000000

In [ ]:
print(data_stat)

    Accuracy
0   0.972222
1   0.972222
2   0.972222
3   1.000000
4   0.916667
5   1.000000
6   0.972222
7   1.000000
8   0.972222
9   0.972222
10  0.944444
11  0.944444
12  0.972222
13  1.000000
14  0.972222
15  0.972222
16  0.972222
17  0.944444
18  0.972222
19  0.972222

#### Taking random state 1

The logistic regression model follows the **logistic (sigmoid) function**, which is given by:

\[
P(Y = 1 \mid X) = \frac{1}{1 + e^{-(\beta_0 + \beta_1 X_1 + \beta_2 X_2 + \dots + \beta_n X_n)}}
\]

where:  
- \( P(Y = 1 \mid X) \) is the probability of the positive class.  
- \( \beta_0 \) is the intercept (bias term).  
- \( \beta_1, \beta_2, \dots, \beta_n \) are the model coefficients (weights).  
- \( X_1, X_2, \dots, X_n \) are the input features.  
- \( e \) is Euler's number (~2.718).  

### **Decision Rule**:
Once we calculate the probability \( P(Y = 1 \mid X) \), we classify the instance as:  
\[
\hat{Y} =
\begin{cases}
1, & \text{if } P(Y = 1 \mid X) \geq 0.5 \\
0, & \text{otherwise}
\end{cases}
\]

This formula is used in the `LogisticRegression` model in your code to predict class labels.

In [ ]:
n=1
X_train, X_test, Y_train, Y_test = train_test_split(X, Y1, test_size=0.25, random_state=n)
model = LogisticRegression(max_iter=1000, random_state=n)
model.fit(X_train, Y_train)
y_test_pred = model.predict(X_test)
accuracy = accuracy_score(Y_test, y_test_pred)
# Extracting the logistic regression formula
coefficients = model.coef_[0]  # Coefficients (weights)
intercept = model.intercept_[0]  # Intercept (bias)
formula_terms = [f"{coef:.4f}*X{i+1}" for i, coef in enumerate(coefficients)]
formula = " + ".join(formula_terms)
equation = f"P(Y=1) = 1 / (1 + exp(-({intercept:.4f} + {formula})))"
print(f"Random State {n}:")
print(f"Logistic Regression Equation:\n{equation}\n")
with open('out.csv', mode='a') as out_file:
  out_writer = csv.writer(out_file, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
  out_writer.writerow([n, accuracy])
copyfile('out.csv', 'out2.csv')

# Import the out.csv file and print the statistics
data_stat = pd.read_csv('out.csv', names=[ "Accuracy"])
print(data_stat.describe())
# Removing out.csv file
try:
    os.remove("out.csv")
except OSError:
    pass

Random State 1:
Logistic Regression Equation:
P(Y=1) = 1 / (1 + exp(-(59.7791 + -1.3922*X1 + -1.6524*X2)))

       Accuracy
count  1.000000
mean   0.972222
std         NaN
min    0.972222
25%    0.972222
50%    0.972222
75%    0.972222
max    0.972222

In [ ]:
# Random State 1:
# Logistic Regression Equation:
# P(Y=1) = 1 / (1 + exp(-(59.7791 + -1.3922*X1 + -1.6524*X2)))

#        Accuracy
# count  1.000000
# mean   0.972222
# std         NaN
# min    0.972222
# 25%    0.972222
# 50%    0.972222
# 75%    0.972222
# max    0.972222

In [ ]:
# Print classification report
print("Classification Report:")
print(classification_report(Y_test, y_test_pred))

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.95      0.98        22
           1       0.93      1.00      0.97        14

    accuracy                           0.97        36
   macro avg       0.97      0.98      0.97        36
weighted avg       0.97      0.97      0.97        36

In [ ]:
# Classification Report:
#               precision    recall  f1-score   support

#            0       1.00      0.95      0.98        22
#            1       0.93      1.00      0.97        14

#     accuracy                           0.97        36
#    macro avg       0.97      0.98      0.97        36
# weighted avg       0.97      0.97      0.97        36

In [ ]:
X1.keys()

Index(['Volume_density_Avg', 'Volume_atom_rad_Avg'], dtype='object')

In [ ]:
# c1 = X1['Volume_density_Avg']
# c2 = X1['Volume_atom_rad_Avg']

## `We have to apply this formula on actual data frame`

In [ ]:
Descriptor = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/GaBP2/GaBP2_2024/2_SMOTE_Data/Descriptor_GaBP2__20_Sep_24.csv")
Descriptor.head()

,compound,BandGap,Volume,vand_rad_Avg,vand_rad_Min,vand_rad_Max,cov_rad_Avg,cov_rad_Min,cov_rad_Max,atom_rad_Avg,atom_rad_Min,atom_rad_Max,density_Avg,density_Min,density_Max
0,ZnGeN2,2.44,181.39,168.33,139,211,104.33,71,122,108.33,65,135,4.42,0.81,7.13
1,ZnGeN2,3.02,181.83,168.33,139,211,104.33,71,122,108.33,65,135,4.42,0.81,7.13
2,ZnGeN2,2.73,181.56,168.33,139,211,104.33,71,122,108.33,65,135,4.42,0.81,7.13
3,AlGaN2,4.59,178.46,175.33,155,187,104.67,71,122,106.67,65,130,3.14,0.81,5.91
4,AlGaN2,4.63,178.36,175.33,155,187,104.67,71,122,106.67,65,130,3.14,0.81,5.91

In [ ]:
# count_series = Descriptor.groupby(['compound','BandGap']).size()
# print(count_series.to_string())

In [ ]:
ML_data1 = Descriptor.copy()

## Removed metalic bandgap

In [ ]:
ML_data1 = ML_data1[ML_data1['BandGap'].between(0.1, 5)]
ML_data1.head(2)

,compound,BandGap,Volume,vand_rad_Avg,vand_rad_Min,vand_rad_Max,cov_rad_Avg,cov_rad_Min,cov_rad_Max,atom_rad_Avg,atom_rad_Min,atom_rad_Max,density_Avg,density_Min,density_Max
0,ZnGeN2,2.44,181.39,168.33,139,211,104.33,71,122,108.33,65,135,4.42,0.81,7.13
1,ZnGeN2,3.02,181.83,168.33,139,211,104.33,71,122,108.33,65,135,4.42,0.81,7.13

In [ ]:
ML_data1['BandGap_class']= ML_data1['BandGap'].apply(lambda z: 0 if z <= 3 else 1)
ML_data1['BandGap_class'].head()

0    0
1    1
2    0
3    1
4    1
Name: BandGap_class, dtype: int64

In [ ]:
ML_data1.head(2)

,compound,BandGap,Volume,vand_rad_Avg,vand_rad_Min,vand_rad_Max,cov_rad_Avg,cov_rad_Min,cov_rad_Max,atom_rad_Avg,atom_rad_Min,atom_rad_Max,density_Avg,density_Min,density_Max,BandGap_class
0,ZnGeN2,2.44,181.39,168.33,139,211,104.33,71,122,108.33,65,135,4.42,0.81,7.13,0
1,ZnGeN2,3.02,181.83,168.33,139,211,104.33,71,122,108.33,65,135,4.42,0.81,7.13,1

In [ ]:
ML_data1['Volume_density_Avg_cbrt']= (np.cbrt(ML_data1['Volume']*ML_data1['density_Avg'])).round(decimals = 2)
#ML_data1['Volume_density_Avg_cbrt']= ML_data1['Volume_density_Avg'].round(decimals = 2)
ML_data1['Volume_atom_rad_Avg_cbrt']= (np.cbrt(ML_data1['Volume']*ML_data1['atom_rad_Avg'])).round(decimals = 2)
#ML_data1['Volume_atom_rad_Avg_cbrt'] = ML_data1['Volume_atom_rad_Avg'].round(decimals = 2)
ML_data1.head()

,compound,BandGap,Volume,vand_rad_Avg,vand_rad_Min,vand_rad_Max,cov_rad_Avg,cov_rad_Min,cov_rad_Max,atom_rad_Avg,atom_rad_Min,atom_rad_Max,density_Avg,density_Min,density_Max,BandGap_class,Volume_density_Avg_cbrt,Volume_atom_rad_Avg_cbrt
0,ZnGeN2,2.44,181.39,168.33,139,211,104.33,71,122,108.33,65,135,4.42,0.81,7.13,0,9.29,26.98
1,ZnGeN2,3.02,181.83,168.33,139,211,104.33,71,122,108.33,65,135,4.42,0.81,7.13,1,9.30,27.01
2,ZnGeN2,2.73,181.56,168.33,139,211,104.33,71,122,108.33,65,135,4.42,0.81,7.13,0,9.29,26.99
3,AlGaN2,4.59,178.46,175.33,155,187,104.67,71,122,106.67,65,130,3.14,0.81,5.91,1,8.24,26.70
4,AlGaN2,4.63,178.36,175.33,155,187,104.67,71,122,106.67,65,130,3.14,0.81,5.91,1,8.24,26.70

In [ ]:
ML_data1.keys()

Index(['compound', 'BandGap', 'Volume', 'vand_rad_Avg', 'vand_rad_Min',
       'vand_rad_Max', 'cov_rad_Avg', 'cov_rad_Min', 'cov_rad_Max',
       'atom_rad_Avg', 'atom_rad_Min', 'atom_rad_Max', 'density_Avg',
       'density_Min', 'density_Max', 'BandGap_class',
       'Volume_density_Avg_cbrt', 'Volume_atom_rad_Avg_cbrt'],
      dtype='object')

In [ ]:
ML_data2 = ML_data1[['compound', 'BandGap','BandGap_class', 'Volume_density_Avg_cbrt', 'Volume_atom_rad_Avg_cbrt']]
ML_data2.head(2)

,compound,BandGap,BandGap_class,Volume_density_Avg_cbrt,Volume_atom_rad_Avg_cbrt
0,ZnGeN2,2.44,0,9.29,26.98
1,ZnGeN2,3.02,1,9.30,27.01

In [ ]:
import numpy as np

# Define the logistic regression parameters
intercept = 59.7791
# Replace X1 and X2 with the corresponding coefficients for:
# c1 = 'Volume_density_Avg' and c2 = 'Volume_atom_rad_Avg'
lasso_coefficients = {
    'Volume_density_Avg_cbrt': -1.3922,
    'Volume_atom_rad_Avg_cbrt': -1.6524
}

# Compute logit(P) for each row in ML_data2
def classify(row):
    # Start with the intercept
    logit_P = intercept

    # Add the weighted contribution from each feature
    logit_P += lasso_coefficients['Volume_density_Avg_cbrt'] * row['Volume_density_Avg_cbrt']
    logit_P += lasso_coefficients['Volume_atom_rad_Avg_cbrt'] * row['Volume_atom_rad_Avg_cbrt']

    # Convert logit to probability using the sigmoid function
    probability = 1 / (1 + np.exp(-logit_P))

    # Assign class based on probability threshold of 0.5
    return 1 if probability > 0.5 else 0

# Example usage:
# Assume X1 is your DataFrame containing 'Volume_density_Avg' and 'Volume_atom_rad_Avg'
ML_data2['Predicted_Class'] = ML_data2.apply(classify, axis=1)

/tmp/ipykernel_406/3845657384.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ML_data2['Predicted_Class'] = ML_data2.apply(classify, axis=1)

In [ ]:
ML_data2.head()

,compound,BandGap,BandGap_class,Volume_density_Avg_cbrt,Volume_atom_rad_Avg_cbrt,Predicted_Class
0,ZnGeN2,2.44,0,9.29,26.98,1
1,ZnGeN2,3.02,1,9.30,27.01,1
2,ZnGeN2,2.73,0,9.29,26.99,1
3,AlGaN2,4.59,1,8.24,26.70,1
4,AlGaN2,4.63,1,8.24,26.70,1

In [ ]:
ML_data2['diff']= abs(ML_data2['BandGap_class']-ML_data2['Predicted_Class'])

/tmp/ipykernel_406/329910619.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ML_data2['diff']= abs(ML_data2['BandGap_class']-ML_data2['Predicted_Class'])

In [ ]:
#print(np.unique(df2['Predicted_Class']))

In [ ]:
#pd.value_counts(df2['Predicted_Class'])

In [ ]:
pd.value_counts(ML_data2['diff'])

/tmp/ipykernel_406/1974610547.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(ML_data2['diff'])

diff
0    76
1     3
Name: count, dtype: int64

In [ ]:
## Result Verify
# count
# diff
# 0	76
# 1	3

In [ ]:
ML_data2.head(100)

,compound,BandGap,BandGap_class,Volume_density_Avg_cbrt,Volume_atom_rad_Avg_cbrt,Predicted_Class,diff
0,ZnGeN2,2.44,0,9.29,26.98,1,1
1,ZnGeN2,3.02,1,9.30,27.01,1,0
2,ZnGeN2,2.73,0,9.29,26.99,1,1
3,AlGaN2,4.59,1,8.24,26.70,1,0
4,AlGaN2,4.63,1,8.24,26.70,1,0
...,...,...,...,...,...,...,...
80,CdSiSb2,0.88,0,14.08,40.16,0,0
81,CdSiSb2,0.75,0,14.08,40.16,0,0
82,ZnSiSb2,0.78,0,13.24,38.28,0,0
83,ZnSiSb2,1.15,0,13.25,38.30,0,0
85,CdGeSb2,0.19,0,15.03,41.18,0,0

In [ ]:
ML_data2.shape

(79, 7)

In [ ]:
72+7

79

In [ ]:
ML_data2.keys()

Index(['compound', 'BandGap', 'BandGap_class', 'Volume_density_Avg_cbrt',
       'Volume_atom_rad_Avg_cbrt', 'Predicted_Class', 'diff'],
      dtype='object')

In [ ]:
ML_data3 = ML_data2[['compound', 'BandGap', 'BandGap_class', 'Predicted_Class']]
ML_data3 = ML_data3.round(decimals = 2)
ML_data3.head()

   compound  BandGap  BandGap_class  Predicted_Class
0  ZnGeN2       2.44              0                1
1  ZnGeN2       3.02              1                1
2  ZnGeN2       2.73              0                1
3  AlGaN2       4.59              1                1
4  AlGaN2       4.63              1                1

In [ ]:
  #print(ML_data3.to_latex(index=True))

In [ ]:
# Convert 'BandGap_class' and 'Predicted_Class' to category dtype
ML_data3[['BandGap_class', 'Predicted_Class']] = ML_data3[['BandGap_class', 'Predicted_Class']].astype('category')
# Format the 'BandGap' column with two decimal places and print the LaTeX output
ML_data3['BandGap'] = ML_data3['BandGap'].apply(lambda x: f"{x:.2f}")
# Print the LaTeX table with the 'BandGap' column formatted
print(ML_data3.to_latex(index=True))

\begin{tabular}{lllll}
\toprule
 & compound & BandGap & BandGap_class & Predicted_Class \\
\midrule
0 & ZnGeN2   & 2.44 & 0 & 1 \\
1 & ZnGeN2   & 3.02 & 1 & 1 \\
2 & ZnGeN2   & 2.73 & 0 & 1 \\
3 & AlGaN2   & 4.59 & 1 & 1 \\
4 & AlGaN2   & 4.63 & 1 & 1 \\
5 & AlGaN2   & 4.46 & 1 & 1 \\
6 & ZnSiN2   & 4.52 & 1 & 1 \\
7 & AlGaAs2   & 1.76 & 0 & 0 \\
8 & AlGaAs2   & 2.06 & 0 & 0 \\
9 & AlGaAs2   & 2.13 & 0 & 0 \\
10 & AlGaP2   & 2.47 & 0 & 0 \\
11 & AlGaP2  & 2.71 & 0 & 0 \\
12 & AlGaP2  & 2.76 & 0 & 0 \\
13 & GaInN2   & 1.32 & 0 & 0 \\
14 & GaInN2   & 1.50 & 0 & 0 \\
15 & GaInN2   & 1.22 & 0 & 0 \\
16 & AlInN2   & 2.64 & 0 & 0 \\
17 & AlInN2   & 3.00 & 0 & 0 \\
18 & AlInN2   & 2.70 & 0 & 0 \\
19 & CdSiN2   & 2.45 & 0 & 1 \\
20 & CdSiN2   & 3.05 & 1 & 1 \\
21 & CdSiN2   & 3.16 & 1 & 1 \\
22 & ZnGeP2   & 0.88 & 0 & 0 \\
23 & ZnGeP2   & 1.73 & 0 & 0 \\
24 & ZnGeP2   & 1.94 & 0 & 0 \\
25 & CdGeN2   & 1.15 & 0 & 0 \\
26 & CdGeN2   & 2.04 & 0 & 0 \\
27 & CdGeN2   & 1.73 & 0 & 0 \\
28 & GaInP2   & 1.87 & 0 & 0 \\
29 & GaInP2   & 2.16 & 0 & 0 \\
30 & GaInP2   & 2.06 & 0 & 0 \\
31 & AlInP2   & 2.62 & 0 & 0 \\
32 & AlInP2   & 2.98 & 0 & 0 \\
33 & AlInP2   & 2.89 & 0 & 0 \\
34 & AlInAs2   & 1.55 & 0 & 0 \\
35 & AlInAs2  & 1.70 & 0 & 0 \\
36 & AlInAs2  & 1.67 & 0 & 0 \\
37 & GaInAs2   & 0.27 & 0 & 0 \\
38 & GaInAs2   & 0.43 & 0 & 0 \\
39 & GaInAs2   & 0.38 & 0 & 0 \\
40 & CdSiAs2   & 0.15 & 0 & 0 \\
41 & CdSiAs2   & 1.47 & 0 & 0 \\
42 & CdSiAs2   & 1.34 & 0 & 0 \\
43 & CdGeAs2   & 0.11 & 0 & 0 \\
46 & ZnGeAs2   & 0.58 & 0 & 0 \\
47 & ZnGeAs2   & 0.50 & 0 & 0 \\
48 & ZnSnN2   & 0.94 & 0 & 0 \\
49 & ZnSnN2   & 0.97 & 0 & 0 \\
50 & ZnSnN2   & 0.79 & 0 & 0 \\
51 & ZnSiAs2   & 0.78 & 0 & 0 \\
52 & ZnSiAs2   & 1.81 & 0 & 0 \\
53 & ZnSiAs2   & 1.95 & 0 & 0 \\
54 & CdSiP2   & 1.21 & 0 & 0 \\
55 & CdSiP2   & 2.70 & 0 & 0 \\
56 & CdSiP2   & 2.33 & 0 & 0 \\
57 & CdGeP2   & 0.36 & 0 & 0 \\
58 & CdGeP2   & 1.78 & 0 & 0 \\
59 & CdGeP2   & 1.62 & 0 & 0 \\
60 & CdSnN2   & 0.10 & 0 & 0 \\
61 & CdSnN2   & 0.45 & 0 & 0 \\
62 & CdSnN2   & 0.15 & 0 & 0 \\
63 & ZnSnAs2   & 0.21 & 0 & 0 \\
64 & ZnSnAs2  & 0.27 & 0 & 0 \\
65 & ZnSnAs2  & 0.24 & 0 & 0 \\
66 & ZnSnP2   & 1.39 & 0 & 0 \\
67 & ZnSnP2   & 1.67 & 0 & 0 \\
68 & ZnSnP2   & 1.69 & 0 & 0 \\
69 & CdSnP2   & 0.75 & 0 & 0 \\
70 & CdSnP2   & 1.29 & 0 & 0 \\
71 & CdSnP2   & 1.14 & 0 & 0 \\
72 & ZnSiP2   & 1.53 & 0 & 0 \\
73 & ZnSiP2   & 2.35 & 0 & 0 \\
74 & ZnSiP2   & 2.20 & 0 & 0 \\
77 & CdSnAs2   & 0.13 & 0 & 0 \\
80 & CdSiSb2  & 0.88 & 0 & 0 \\
81 & CdSiSb2  & 0.75 & 0 & 0 \\
82 & ZnSiSb2   & 0.78 & 0 & 0 \\
83 & ZnSiSb2   & 1.15 & 0 & 0 \\
85 & CdGeSb2   & 0.19 & 0 & 0 \\
\bottomrule
\end{tabular}

# `The Model Failure Class`

In [ ]:
ML_data3 = ML_data2.copy()
ML_data3.head()

,compound,BandGap,BandGap_class,Volume_density_Avg_cbrt,Volume_atom_rad_Avg_cbrt,Predicted_Class,diff
0,ZnGeN2,2.44,0,9.29,26.98,1,1
1,ZnGeN2,3.02,1,9.30,27.01,1,0
2,ZnGeN2,2.73,0,9.29,26.99,1,1
3,AlGaN2,4.59,1,8.24,26.70,1,0
4,AlGaN2,4.63,1,8.24,26.70,1,0

In [ ]:
ML_data4 = ML_data3[ML_data3['diff'] != 0]
ML_data4

,compound,BandGap,BandGap_class,Volume_density_Avg_cbrt,Volume_atom_rad_Avg_cbrt,Predicted_Class,diff
0,ZnGeN2,2.44,0,9.29,26.98,1,1
2,ZnGeN2,2.73,0,9.29,26.99,1,1
19,CdSiN2,2.45,0,9.05,27.49,1,1

In [ ]:
import numpy as np

# Define the logistic regression parameters
intercept = 59.7791
# Replace X1 and X2 with the corresponding coefficients for:
# c1 = 'Volume_density_Avg' and c2 = 'Volume_atom_rad_Avg'
lasso_coefficients = {
    'Volume_density_Avg_cbrt': -1.3922,
    'Volume_atom_rad_Avg_cbrt': -1.6524
}

# Compute logit(P) for each row in ML_data2
def classify(row):
    # Start with the intercept
    logit_P = intercept

    # Add the weighted contribution from each feature
    logit_P += lasso_coefficients['Volume_density_Avg_cbrt'] * row['Volume_density_Avg_cbrt']
    logit_P += lasso_coefficients['Volume_atom_rad_Avg_cbrt'] * row['Volume_atom_rad_Avg_cbrt']

    # Convert logit to probability using the sigmoid function
    probability = 1 / (1 + np.exp(-logit_P))

    # Assign class based on probability threshold of 0.5
    return 1 if probability > 0.5 else 0

# Example usage:
# Assume X1 is your DataFrame containing 'Volume_density_Avg' and 'Volume_atom_rad_Avg'
ML_data4['Predicted_Class1'] = ML_data4.apply(classify, axis=1)

/tmp/ipykernel_406/1243659679.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ML_data4['Predicted_Class1'] = ML_data4.apply(classify, axis=1)

In [ ]:
ML_data4

,compound,BandGap,BandGap_class,Volume_density_Avg_cbrt,Volume_atom_rad_Avg_cbrt,Predicted_Class,diff,Predicted_Class1
0,ZnGeN2,2.44,0,9.29,26.98,1,1,1
2,ZnGeN2,2.73,0,9.29,26.99,1,1,1
19,CdSiN2,2.45,0,9.05,27.49,1,1,1